version: 2.1

jobs:
  publish:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: grep -oP 'version\": \"\K[0-9]*.[0-9]*.[0-9]*' AutoTabGroup/manifest.json

workflows:
  publish:
    jobs:
      - publish